from fastapi import APIRouter

from app.api.v1 import (
    alerts,
    auth,
    companies,
    driver_fatigue,
    driver_pay_rates,
    drivers,
    expense_concepts,
    fatigue_rules,
    gps_providers,
    gps_webhook,
    holidays,
    inventory_items,
    inventory_movements,
    maintenance,
    providers,
    rate_tables,
    roles,
    routes,
    tire_movements,
    tire_settings,
    tires,
    trip_documents,
    trips,
    users,
    vehicle_positions,
    vehicles,
    warehouses,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(companies.router)
api_router.include_router(users.router)
api_router.include_router(roles.router)
api_router.include_router(vehicles.router)
api_router.include_router(driver_fatigue.router)
api_router.include_router(drivers.router)
api_router.include_router(providers.router)
api_router.include_router(maintenance.router)
api_router.include_router(alerts.router)
api_router.include_router(rate_tables.router)
api_router.include_router(driver_pay_rates.router)
api_router.include_router(holidays.router)
api_router.include_router(expense_concepts.router)
api_router.include_router(trips.router)
api_router.include_router(trip_documents.router)
api_router.include_router(gps_providers.router)
api_router.include_router(gps_webhook.router)
api_router.include_router(vehicle_positions.router)
api_router.include_router(fatigue_rules.router)
api_router.include_router(driver_fatigue.router)
api_router.include_router(warehouses.router)
api_router.include_router(tires.router)
api_router.include_router(tire_movements.router)
api_router.include_router(tire_settings.router)
api_router.include_router(inventory_items.router)
api_router.include_router(inventory_movements.router)
api_router.include_router(routes.router)
