"""phase 2: trips, trip expenses, trip payroll, rate tables, driver pay rates, holidays, expense concepts

Revision ID: 000a185731a9
Revises: 37bca27dc2ed
Create Date: 2026-07-18 16:04:37.627647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000a185731a9'
down_revision: Union[str, None] = '37bca27dc2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_holidays',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_company_holidays_date')
    )
    op.create_table('driver_pay_rates',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('daily_base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meal_allowance_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_bonus_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('return_bonus_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vehicle_type IN ('camion', 'remolque', 'cabezal')", name='ck_driver_pay_rates_vehicle_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'vehicle_type', name='uq_driver_pay_rates_type')
    )
    op.create_table('expense_concepts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_expense_concepts_name')
    )
    op.create_table('rate_tables',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vehicle_type IN ('camion', 'remolque', 'cabezal')", name='ck_rate_tables_vehicle_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'origin', 'destination', 'vehicle_type', 'cargo_type', name='uq_rate_tables_route')
    )
    op.create_table('trips',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('trailer_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_odometer_km', sa.Integer(), nullable=True),
    sa.Column('end_odometer_km', sa.Integer(), nullable=True),
    sa.Column('freight_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planificado', 'en_curso', 'completado', 'cancelado')", name='ck_trips_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trailer_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_company_status', 'trips', ['company_id', 'status'], unique=False)
    op.create_index('ix_trips_driver_id', 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_vehicle_id', 'trips', ['vehicle_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['expense_concepts.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_payroll',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meal_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('return_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonuses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_to_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_payroll')
    op.drop_table('trip_expenses')
    op.drop_index('ix_trips_vehicle_id', table_name='trips')
    op.drop_index('ix_trips_driver_id', table_name='trips')
    op.drop_index('ix_trips_company_status', table_name='trips')
    op.drop_table('trips')
    op.drop_table('rate_tables')
    op.drop_table('expense_concepts')
    op.drop_table('driver_pay_rates')
    op.drop_table('company_holidays')
    # ### end Alembic commands ###
