"""phase 4: fatigue rules and driver fatigue logs

Revision ID: 166bf8eb16cd
Revises: 6988d8bf8e5d
Create Date: 2026-07-18 21:32:39.534374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '166bf8eb16cd'
down_revision: Union[str, None] = '6988d8bf8e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se removieron del autogenerate los drop/create de las particiones mensuales de
    # vehicle_positions (vehicle_positions_y2026m07/08/09) — no son parte de los metadatos de
    # SQLAlchemy (se crean con DDL crudo, ver la migración de Fase 3), así que autogenerate las
    # detecta como "tablas no declaradas" y las quiere borrar. No tocar esas particiones aquí.
    op.create_table('fatigue_rules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('max_continuous_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_24h_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_7day_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('night_driving_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('night_start_hour', sa.SmallInteger(), nullable=False),
    sa.Column('night_end_hour', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('driver_fatigue_logs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('continuous_driving_min', sa.Integer(), nullable=False),
    sa.Column('total_24h_min', sa.Integer(), nullable=False),
    sa.Column('total_7day_min', sa.Integer(), nullable=False),
    sa.Column('night_driving_min', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('bajo', 'medio', 'alto', 'critico')", name='ck_driver_fatigue_logs_risk_level'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'date', name='uq_driver_fatigue_logs_driver_date')
    )
    op.create_index('ix_driver_fatigue_logs_driver_date', 'driver_fatigue_logs', ['driver_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_fatigue_logs_driver_date', table_name='driver_fatigue_logs')
    op.drop_table('driver_fatigue_logs')
    op.drop_table('fatigue_rules')
    # ### end Alembic commands ###
