"""phase 1: vehicles, drivers, providers, maintenance, alerts

Revision ID: 37bca27dc2ed
Revises: 1da6bb01f79c
Create Date: 2026-07-18 15:38:14.567221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37bca27dc2ed'
down_revision: Union[str, None] = '1da6bb01f79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("severity IN ('baja', 'media', 'alta')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('no_leida', 'leida')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_company_status_created', 'alerts', ['company_id', 'status', 'created_at'], unique=False)
    op.create_index('uq_alerts_unread_dedupe', 'alerts', ['company_id', 'type', 'entity_id'], unique=True, postgresql_where=sa.text("status = 'no_leida'"))
    op.create_table('drivers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('activo', 'suspendido', 'inactivo')", name='ck_drivers_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'license_number', name='uq_drivers_company_license')
    )
    op.create_table('providers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_odometer_km', sa.Integer(), nullable=False),
    sa.Column('assigned_driver_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('activo', 'taller', 'inactivo')", name='ck_vehicles_status'),
    sa.CheckConstraint("type IN ('camion', 'remolque', 'cabezal')", name='ck_vehicles_type'),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'plate', name='uq_vehicles_company_plate')
    )
    op.create_table('maintenance_tasks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_by', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scheduled_by = 'tiempo' AND due_date IS NOT NULL) OR (scheduled_by = 'km' AND due_km IS NOT NULL)", name='ck_maintenance_tasks_due_matches_scheduled_by'),
    sa.CheckConstraint("scheduled_by IN ('tiempo', 'km')", name='ck_maintenance_tasks_scheduled_by'),
    sa.CheckConstraint("status IN ('pendiente', 'en_proceso', 'completada', 'vencida', 'cancelada')", name='ck_maintenance_tasks_status'),
    sa.CheckConstraint("type IN ('preventivo', 'correctivo')", name='ck_maintenance_tasks_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('cost_labor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_parts', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_records')
    op.drop_table('maintenance_tasks')
    op.drop_table('vehicles')
    op.drop_table('providers')
    op.drop_table('drivers')
    op.drop_index('uq_alerts_unread_dedupe', table_name='alerts', postgresql_where=sa.text("status = 'no_leida'"))
    op.drop_index('ix_alerts_company_status_created', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
