"""phase 9b delivery orders

Revision ID: 3be1041184dd
Revises: e9e841bbaf06
Create Date: 2026-07-20 14:25:49.318048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3be1041184dd'
down_revision: Union[str, None] = 'e9e841bbaf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_orders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_by', sa.UUID(), nullable=True),
    sa.Column('delivery_proof_url', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pendiente', 'asignado', 'en_ruta', 'entregado', 'fallido')", name='ck_delivery_orders_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_order_items',
    sa.Column('delivery_order_id', sa.UUID(), nullable=False),
    sa.Column('goods_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goods_id'], ['delivery_goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: se omiten las particiones mensuales de vehicle_positions (runtime, no metadata) — mismo
    # criterio que las migraciones de Fase 8/9A.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('delivery_order_items')
    op.drop_table('delivery_orders')
