"""phase 5: warehouses, tires, tire movements, tire settings

Revision ID: 689d55e81292
Revises: 166bf8eb16cd
Create Date: 2026-07-18 23:21:56.375581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689d55e81292'
down_revision: Union[str, None] = '166bf8eb16cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se removieron del autogenerate los drop/create de las particiones mensuales de
    # vehicle_positions (vehicle_positions_y2026m07/08/09) — no son parte de los metadatos de
    # SQLAlchemy (se crean con DDL crudo, ver la migración de Fase 3), así que autogenerate las
    # detecta como "tablas no declaradas" y las quiere borrar. No tocar esas particiones aquí
    # (mismo ajuste que en la migración de Fase 4).
    op.create_table('tire_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('disparity_threshold_mm', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('warehouses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_warehouses_company_name')
    )
    op.create_table('tires',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('current_thickness_mm', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('axle_number', sa.SmallInteger(), nullable=True),
    sa.Column('axle_side', sa.String(length=10), nullable=True),
    sa.Column('axle_dual_position', sa.String(length=10), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("axle_dual_position IN ('unico', 'interior', 'exterior')", name='ck_tires_axle_dual_position'),
    sa.CheckConstraint("axle_side IN ('izquierdo', 'derecho', 'unico')", name='ck_tires_axle_side'),
    sa.CheckConstraint("status IN ('instalado', 'almacen', 'reparacion')", name='ck_tires_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'unique_code', name='uq_tires_company_unique_code')
    )
    op.create_table('tire_movements',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tire_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('axle_number', sa.SmallInteger(), nullable=True),
    sa.Column('axle_side', sa.String(length=10), nullable=True),
    sa.Column('axle_dual_position', sa.String(length=10), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('km_at_movement', sa.Integer(), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("axle_dual_position IN ('unico', 'interior', 'exterior')", name='ck_tire_movements_axle_dual_position'),
    sa.CheckConstraint("axle_side IN ('izquierdo', 'derecho', 'unico')", name='ck_tire_movements_axle_side'),
    sa.CheckConstraint("movement_type IN ('instalacion', 'desinstalacion', 'envio_reparacion', 'envio_reencauche', 'retorno_taller')", name='ck_tire_movements_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tire_id'], ['tires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tire_movements')
    op.drop_table('tires')
    op.drop_table('warehouses')
    op.drop_table('tire_settings')
    # ### end Alembic commands ###
