"""phase 3: gps providers, vehicle map, vehicle_positions (partitioned)

Revision ID: 6988d8bf8e5d
Revises: 000a185731a9
Create Date: 2026-07-18 16:52:38.352035

"""
from datetime import date, datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6988d8bf8e5d'
down_revision: Union[str, None] = '000a185731a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_bounds(base: date, offset: int) -> tuple[date, date]:
    """Rango [start, end) del mes `base` + `offset` meses, para una partición mensual."""
    month_index = base.month - 1 + offset
    year = base.year + month_index // 12
    month = month_index % 12 + 1
    start = date(year, month, 1)
    end = date(year + 1, 1, 1) if month == 12 else date(year, month + 1, 1)
    return start, end


def _create_monthly_partition(offset: int) -> None:
    today = datetime.now(timezone.utc).date()
    start, end = _month_bounds(today, offset)
    partition_name = f"vehicle_positions_y{start.year}m{start.month:02d}"
    op.execute(
        f"CREATE TABLE {partition_name} PARTITION OF vehicle_positions "
        f"FOR VALUES FROM ('{start.isoformat()}') TO ('{end.isoformat()}')"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_providers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_type', sa.String(length=50), nullable=False),
    sa.Column('api_credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('ingestion_mode', sa.String(length=10), nullable=False),
    sa.Column('webhook_token_hash', sa.String(length=64), nullable=True),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_mode IN ('webhook', 'polling')", name='ck_gps_providers_ingestion_mode'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'provider_name', name='uq_gps_providers_company_name')
    )
    op.create_table('gps_provider_vehicle_map',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('external_device_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['gps_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_device_id', name='uq_gps_map_provider_device'),
    sa.UniqueConstraint('provider_id', 'vehicle_id', name='uq_gps_map_provider_vehicle')
    )
    op.create_table('vehicle_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('ignition_status', sa.Boolean(), nullable=True),
    sa.Column('heading', sa.SmallInteger(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['gps_providers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_index('ix_vehicle_positions_company_ts', 'vehicle_positions', ['company_id', 'timestamp'], unique=False)
    op.create_index('ix_vehicle_positions_vehicle_ts', 'vehicle_positions', ['vehicle_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###

    # Particiones mensuales: mes actual + 2 siguientes. El job de app/jobs/gps_partitions.py
    # crea la del mes N+3 cada vez que arranca un mes nuevo, para que nunca falte partición.
    for offset in range(3):
        _create_monthly_partition(offset)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_positions_vehicle_ts', table_name='vehicle_positions')
    op.drop_index('ix_vehicle_positions_company_ts', table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    op.drop_table('gps_provider_vehicle_map')
    op.drop_table('gps_providers')
    # ### end Alembic commands ###
