"""config b form rules

Revision ID: 772cad34d9c4
Revises: ae446ba4ea4d
Create Date: 2026-07-21 08:19:08.282217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772cad34d9c4'
down_revision: Union[str, None] = 'ae446ba4ea4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_rules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('vehicle', 'driver', 'trip', 'delivery_order', 'client', 'maintenance_task', 'inventory_item', 'tire', 'delivery_goods')", name='ck_form_rules_entity_type'),
    sa.CheckConstraint("kind IN ('formulario', 'validacion')", name='ck_form_rules_kind'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: se omiten las particiones mensuales de vehicle_positions (runtime, no metadata) — mismo
    # criterio que las migraciones anteriores.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('form_rules')
