"""config a custom fields

Revision ID: ae446ba4ea4d
Revises: 0b3c81ef6b40
Create Date: 2026-07-20 18:51:31.841046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # noqa: F401 — usado por los tipos JSONB de add_column

# revision identifiers, used by Alembic.
revision: str = 'ae446ba4ea4d'
down_revision: Union[str, None] = '0b3c81ef6b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('vehicle', 'driver', 'trip', 'delivery_order', 'client', 'maintenance_task', 'inventory_item', 'tire', 'delivery_goods')", name='ck_custom_fields_entity_type'),
    sa.CheckConstraint("field_type IN ('texto', 'numero', 'fecha', 'select', 'checkbox', 'area_texto')", name='ck_custom_fields_field_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'entity_type', 'key', name='uq_custom_fields_company_entity_key')
    )
    # NOTA: se omiten las particiones mensuales de vehicle_positions (runtime, no metadata) — mismo
    # criterio que las migraciones de fases anteriores.
    op.add_column('clients', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('delivery_goods', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('delivery_orders', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('drivers', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('inventory_items', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('maintenance_tasks', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tires', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('trips', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('vehicles', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'custom_data')
    op.drop_column('trips', 'custom_data')
    op.drop_column('tires', 'custom_data')
    op.drop_column('maintenance_tasks', 'custom_data')
    op.drop_column('inventory_items', 'custom_data')
    op.drop_column('drivers', 'custom_data')
    op.drop_column('delivery_orders', 'custom_data')
    op.drop_column('delivery_goods', 'custom_data')
    op.drop_column('clients', 'custom_data')
    op.drop_table('custom_field_definitions')
