"""phase 9a delivery goods catalog

Revision ID: e9e841bbaf06
Revises: c61ba31333dd
Create Date: 2026-07-20 13:57:08.447253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e9e841bbaf06'
down_revision: Union[str, None] = 'c61ba31333dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_goods',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_kg_per_unit', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('volume_m3_per_unit', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_delivery_goods_company_sku')
    )
    op.create_table('delivery_goods_movements',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('goods_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_doc', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("movement_type IN ('entrada', 'salida', 'ajuste')", name='ck_delivery_goods_movements_type'),
    sa.CheckConstraint('quantity <> 0', name='ck_delivery_goods_movements_quantity_nonzero'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goods_id'], ['delivery_goods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: se omiten las particiones mensuales de vehicle_positions que autogenerate detecta como
    # "removidas" (las crea en runtime app/jobs/gps_partitions.py, no la metadata de SQLAlchemy) —
    # mismo criterio que la migración de Fase 8.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('delivery_goods_movements')
    op.drop_table('delivery_goods')
